- name: Clean output folder
  run: rm -rf ./output

- name: Publish
  run: dotnet publish Az204Api.csproj --configuration Release --output ./output

- name: List published files
  run: ls -R ./output

- name: Deploy to Azure WebApp
  uses: azure/webapps-deploy@v2
  with:
    app-name: az204webapp17949
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    package: ./output